spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    #    url: jdbc:mysql://host.docker.internal:3309/recipe_2_plate?allowPublicKeyRetrieval=true&useSSL=false
    #    url: jdbc:mysql://host.docker.internal:3309/recipe_2_plate?allowPublicKeyRetrieval=true&useSSL=false
    url: jdbc:mysql://localhost:3306/recipe?allowPublicKeyRetrieval=true&useSSL=false
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
        show_sql: true


  #  flyway:
  #    user: root
  #    password: root
  #    url: jdbc:mysql://localhost:3306/recipe?allowPublicKeyRetrieval=true&useSSL=false
  #    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
      enabled: true


server:
  servlet:
    context-path: "/api"
  port: 9042


security.jwt.token.secret-key: qwemqkweqtqkjeqkwehqbgtqkwjeqlkjw


